language: go
node_js:
 - "4"

addons:
  apt:
    packages:
      - xvfb
      - imagemagick

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  
script:
  - npm install -g electron
  - chmod +x build_osmesa.sh
  - ./build_osmesa.sh
  - chmod +x test.sh
  - npm test
