language: go
node_js:
 - "4"

addons:
  apt:
    packages:
      - xvfb
      - imagemagick

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 640x480x24 > /dev/null 2>&1 &
  
script:
  - npm install
  - chmod +x build_osmesa.sh
  - ./build_osmesa.sh
  - cp libosmesa.so `npm config get prefix`/lib/node_modules/electron/dist
  - chmod +x test.sh
  - npm test
